version: 2
jobs:
  test:
    docker:
      - image: circleci/php:7.4-cli
    steps:
      - run:
          name: Install Packages & Extensions
          command: |
            sudo apt-get update
            sudo apt-get install libpng-dev
            sudo docker-php-ext-install gd
      - run:
          name: Clone October
          command: |
            git clone https://github.com/octobercms/october.git
      - run:
          name: Clone Plugins
          command: |
            git clone -b ${CIRCLE_BRANCH} https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} ./october/plugins/bedard/example
      - restore_cache:
          key: -v3-{{ checksum "october/composer.json" }}-{{ checksum "october/plugins/bedard/example/composer.lock" }}
      - run:
          name: Install Dependencies
          command: |
            (cd ./october && composer install)
            (cd ./october/plugins/bedard/example && composer install)
      - save_cache:
          key: -v3-{{ checksum "october/composer.json" }}-{{ checksum "october/plugins/bedard/example/composer.lock" }}
          paths:
            - "october/vendor"
            - "october/plugins/bedard/example/vendor"
      - run:
          name: Test
          command: |
            cd ./october/plugins/bedard/example
            phpdbg -qrr vendor/bin/phpunit -d memory_limit=512M --coverage-clover clover.xml
      - run:
          name: Codecov
          command: |
            cd ./october/plugins/bedard/example
            bash <(curl -s https://codecov.io/bash) -v -cF php
workflows:
  version: 2
  tests:
    jobs:
      - test