version: 2
jobs:
  test:
    docker:
      - image: circleci/php:7.4-cli
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install libpng-dev
      - run:
          name: Install PHP Extensions
          command: sudo docker-php-ext-install gd
      - run:
          name: Clone October
          command: |
            git clone https://github.com/octobercms/october.git
      - restore_cache:
          key: -v3-{{ checksum "october/composer.json" }}-{{ checksum "october/plugins/bedard/example/composer.lock" }}
      # - run:
      #     name: Clone plugins
      #     command: |
      #       git clone https://github.com/rainlab/user-plugin.git ./october/plugins/rainlab/user
      - run:
          name: Install dependencies
          command: |
            (cd ./october && composer install)
            (cd ./october/plugins/bedard/example && composer install)
      - save_cache:
          key: -v3-{{ checksum "october/composer.json" }}-{{ checksum "october/plugins/bedard/example/composer.lock" }}
          paths:
            - "october/vendor"
            - "october/plugins/bedard/example/vendor"
      - run:
          name: Test
          command: |
            cd ./october/plugins/bedard/example
            phpdbg -qrr vendor/bin/phpunit -d memory_limit=512M --coverage-clover clover.xml
      # - run:
      #     name: Codecov
      #     command: |
      #       cd ./october/plugins/bedard/example
      #       bash <(curl -s https://codecov.io/bash) -v -cF php
workflows:
  version: 2
  tests:
    jobs:
      - test